# Generated by Django 5.0.6 on 2024-06-13 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('letters', models.CharField(max_length=9)),
                ('numbers', models.CharField(max_length=20)),
                ('num_target', models.IntegerField(default=150)),
                ('conundrum', models.CharField(max_length=9)),
                ('score_letters', models.IntegerField(null=True)),
                ('score_numbers', models.IntegerField(null=True)),
                ('score_conundrum', models.IntegerField(null=True)),
                ('score_total', models.IntegerField(null=True)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_game', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
