# Generated by Django 5.0.6 on 2024-06-21 01:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_game',
            name='player',
        ),
        migrations.AddField(
            model_name='daily_game',
            name='players',
            field=models.ManyToManyField(related_name='daily_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
