# Generated by Django 5.0.6 on 2024-06-21 01:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_game', '0002_remove_daily_game_player_daily_game_players'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_game',
            name='players',
        ),
        migrations.AddField(
            model_name='daily_game',
            name='player',
            field=models.ManyToManyField(related_name='daily_game', to=settings.AUTH_USER_MODEL),
        ),
    ]
