# Generated by Django 5.0.6 on 2024-06-22 01:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_game', '0003_remove_daily_game_players_daily_game_player'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_game',
            name='player',
            field=models.ManyToManyField(null=True, related_name='daily_game', to=settings.AUTH_USER_MODEL),
        ),
    ]
