# Generated by Django 4.2 on 2024-06-25 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daily_game', '0004_alter_daily_game_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_game',
            name='player',
            field=models.ManyToManyField(related_name='daily_game', to=settings.AUTH_USER_MODEL),
        ),
    ]
