# Generated by Django 4.2 on 2024-06-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_game', '0006_remove_daily_game_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_game',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
