# Generated by Django 4.2 on 2024-06-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_game', '0007_alter_daily_game_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plays',
            options={'verbose_name_plural': 'plays'},
        ),
    ]
