# Generated by Django 4.2 on 2024-06-28 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily_game', '0008_alter_plays_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plays',
            name='game_played',
        ),
        migrations.AddField(
            model_name='plays',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_played', to='daily_game.daily_game'),
        ),
    ]
