# Generated by Django 4.2 on 2024-06-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_game', '0010_alter_daily_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_game',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
